print 'this is your horoscope'
print 'You will win theLotterey if you are lucky'
print 'You will win theLotterey if you are lucky'
print 'You will win theLotterey if you are lucky'
print 'You will win theLotterey if you are lucky'
print 'You will win theLotterey if you are lucky'
print 'You will win theLotterey if you are lucky'
